### PR TITLE
Us221 form state management update

### PR DESCRIPTION
**Pull request by aschnapp**
## Overview
This is part of US221 that changes the default form data to user defined form data in the edit component.
Also merges create/ and edit/ into forms.vue.

## Includes:
New file: views/Forms.vue
Every form has been changed, unused ones deleted.
Other places may be changed too, please see files tab.

## Developer Checklist:
- [x] The code follows the Quality Policy file on Google Drive
- [] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

## Notes:
When reviewing, please double check that each form component is working correctly, and that state is properly cloned. There's a lot, I hope I didnt miss anything. 

## Refs:
- [US 216](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-221)

### CODE REVIEW

**Review by aneuhold — CHANGES_REQUESTED** [review]
This looks pretty good so far. @aschnapp can it have dev merged into it please? It seems like that will cause a few changes.

**Comment by aschnapp** [comment]
@aneuhold done. Does it help?

**Comment by aneuhold** [comment]
@aschnapp when creating a new model, when no other models exist, the console shows the following error after clicking "create":

error

This error seems to keep happening when a form is edited too. 

Also when clicking on the form names, it no longer jumps to the location of those forms, but the URL does change. 

https://user-images.githubusercontent.com/17774559/107090898-bd716980-67b5-11eb-8547-8b6eabbb0871.mov

**Comment by aneuhold** [comment]
Also, there is an error bug with the plot not displaying right but that will be fixed with a PR that will come out today or tomorrow.

**Comment by aschnapp** [comment]
> @aschnapp when creating a new model, when no other models exist, the console shows the following error after clicking "create":
> 
> error
> 
> This error seems to keep happening when a form is edited too.
> 
> Also when clicking on the form names, it no longer jumps to the location of those forms, but the URL does change.
> Screen.Recording.2021-02-05.at.1.25.39.PM.mov

@aneuhold this pr only fixes what the stuff I stated above. Not other existing problems in dev. 
If the quoted problem already happens in dev, this will not fix it. It's for another US in dev.

**Comment by Tengelma** [comment]
> > @aschnapp when creating a new model, when no other models exist, the console shows the following error after clicking "create":
> > error
> > This error seems to keep happening when a form is edited too.
> > Also when clicking on the form names, it no longer jumps to the location of those forms, but the URL does change.
> > Screen.Recording.2021-02-05.at.1.25.39.PM.mov
> 
> @aneuhold this pr only fixes what the stuff I stated above. Not other existing problems in dev.
> If the quoted problem already happens in dev, this will not fix it. It's for another user story.

@mschnapp none of the things he's mentioned are issues on dev

**Comment by Tengelma** [comment]
@aneuhold the scrolling is working fine when I run this locally.

**Review by Tengelma — APPROVED** [review]
@aneuhold I resolved the thing causing the console warning (bug that I introduced in early commits on this branch) and scrolling seems to be working fine for me. Can you check again?

Approving.

**Comment by aschnapp** [comment]
@aneuhold Sorry I thought you were talking about errors when changing stuff in dropdowns. 
Scrolling is working fine for me too. I'm running MacOS Big Sur with Chrome.

**Comment by aneuhold** [comment]
@aschnapp @Tengelma the error looks to be fixed now, but the scrolling issue still seems to be there, but isn't there on dev. More specifically, it only looks to happen when a model is edited. When creating a new model, the scrolling works, and when refreshing the page while editing a model, the scrolling works again too. But when editing a model from the main page it doesn't. Mac OS Big Sur, Chrome. Please see video below:

[Short video of the issue](https://i.imgur.com/K2tARPb.mp4)

**Comment by aneuhold** [comment]
Never mind. It isn't working on dev either. So it seems to not be working in both spots. @aschnapp @Tengelma, you both can click on an item in the left hand menu right after clicking on the edit icon for a model and it will scroll down to that location?

**Comment by aschnapp** [comment]
@aneuhold @Tengelma lets move this conversation to slack. 
It is working for me though..

**Review by aneuhold — APPROVED** [review]

**Pull request merged**
