### PR TITLE
Final Merge from Dev into Main

### PR DESCRIPTION
**Pull request by aneuhold**
### Overview
The final pull from dev into main. After this PR is resolved, all PRs should be built so that they merge into main, per the discussions of the team at the last sponsor meeting 😄 .

@steven-murray if you could run this through its paces and try to break it any way you can, that would be ideal before merging this so that any last issues can be fixed before the project gets moved to the main domain name 😄 .

Also, as a side note, I setup a notification on [uptimerobot](https://uptimerobot.com/) for `api.thehalomod.app` so that it would shoot me an email if it ever goes down for some reason. It might be good for you to do that as well if you are interested. 

### Developer Checklist:
- [x] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

### CODE REVIEW

**Comment by steven-murray** [comment]
Thanks @aneuhold. I'll give it a good thorough check ASAP. I am out for the next few days, so probably won't get back to it til next Wednesday.

**Review by steven-murray — COMMENTED** [review]
Things I noticed while playing with it:

- [x] There is still no initial model -- is this still an open issue?
- [x] When choosing a new X-axis on the dropdown, the plot doesn't update. It only updates after you choose a new Y-axis.
- [ ] When choosing a new X-axis that is compatible with the previous one, the initial Y-axis choice should stay the same, instead of going back to the default for that choice. If this is tricky, we can make it an issue rather than solving it here.
- [x] Can we make the default action of "Enter" on the form page be to submit the form?
- [ ] Would be great if after sending a bug report on a model, it came up with a thank you message on the left under the model box.
- [x] **CRITICAL**: there's something wrong with the comoving r range. I think perhaps we're taking it as log instead of log10? By default, it should extend past r=100 (i.e. 10^2)
- [x] **CRITICAL**: Downloading "Vector Data" doesn't seem to work.

**Comment by steven-murray** [comment]
@aneuhold let me know which things you'd like me to try and tackle, and which things might be best left for future issues. I might have some time on Friday to try a few things out.

**Comment by aneuhold** [comment]
@steven-murray 

That is a helpful list. Thank you.

1. During the second to final meeting it sounded like we came to the conclusion that because of the overhead of implementing an initial model on the client side, it would be implemented on the server side only. See [this comment](https://github.com/halomod/TheHaloMod-SPA/issues/139#issuecomment-812902097) for more info on the needs there if it were to be implemented on the client side. Is this something that should be done before it is released? If so, that can be worked on. 
2. The drop-down is admittedly not intuitive in how that functions. This can be worked on as well. 
3. Same goes with the updated x-axis that is compatible. 
4. Yes, that should be easy. If you want to give this one a shot you can. 
5. This sounds relatively easy, personally going to be working on the other things first though. If you want to give this one a shot as well, that would work well 😄 
6. Going to be looking into this first.
7. Going to be looking into this second.

**Comment by steven-murray** [comment]
Thanks @aneuhold. Yes, if you can look at the last two, I'll try looking at 4+5. Neither of these are critical though -- if I can't get to them this week, I say we make them issues and merge. Just the critical ones are needed.

As for the initial model -- it sounds like we have a pre-computed model on the server that we clone to make new models when sent from the client. This makes sense, and is really probably good enough.

**Comment by aschnapp** [comment]
I'll looking into 2+3 later this weekend.

**Comment by aneuhold** [comment]
@aschnapp already working on 2+3 and almost finished at the moment.

**Comment by aneuhold** [comment]
@aschnapp if you want to work on a PR that makes sure the docker container is watched and brought back up if it goes down that would be helpful.

**Comment by aschnapp** [comment]
@aneuhold OK

**Comment by aschnapp** [comment]
@steven-murray @aneuhold the auto restart is done in #172

**Comment by aneuhold** [comment]
@steven-murray the auto-restart was implemented and the server is back up now. Somewhere along the line an SSL dependency was removed from `requirements.txt` so that was causing some problems with it coming back up.

**Comment by steven-murray** [comment]
@aneuhold Aha! Great, thanks!

**Comment by aneuhold** [comment]
@steven-murray Hi Steven! Just wanted to check in about this and see if there was anything else that needed to be done before merging into main and deploying it. It seems to be taking a bit longer than expected so if there is something in particular that you want to see done first feel free to bring it up so it can be worked on 😄 .

**Comment by aneuhold** [comment]
Just wasn't working on the active issues until it got deployed to make sure that went smoothly first. But if you would rather have those worked on for now that can be done 😄 .

**Comment by steven-murray** [comment]
Hi @aneuhold. Thanks for checking up on it. Yes, I essentially get a couple of hours a week at most to work on this, so it's slow from my end. As you know, I worked on one of the checklist items, which is now done (thanks for fixing it up!). 

I had another I was going to work on (the "thanks for reporting an error" box). I may be able to try it out tomorrow, but I get the feeling I might not have the time. 

However, are the things I marked as CRITICAL fixed up? If those are done, I say we merge now and add the rest as issues for later.

**Comment by aneuhold** [comment]
@steven-murray yes sir the ones marked as critical are done. Just checked them off. Didn't realize you could mark checkboxes in other people's comments! Haha and no worries about the time commitment. 

Alright, going to merge now then!

**Pull request merged**
