### PR TITLE
US276 Fix DoubleField

### PR DESCRIPTION
**Pull request by Tengelma**
### Overview
This is a weird one, folks. DoubleField has been fixed but the only way to do so was to break most existing forms (and many of their tests). Since I'll be diving into generic forms within the next couple of days it didn't make sense to me to manually fix everything in every single form when its about to be replaced anyway. 

As a result, I've created a 'GenericForms' branch which will keep all work related to that tucked away until we can merge it all into dev and I am merging this branch into GenericForms instead of dev.

This PR does a lot:
- introduces a new validator isDefined that verifies that a field isn't empty.
- provides extensive tests for our form validators
- implements a revised DoubleField class that resolves the bug discussed on Monday
- includes extensive tests for the DoubleField class to verify that everything works as expected
- comes with a revised BiasForm class that accomodates the updated DoubleField class as a demo of it actually being fixed
- comments out all forms except BiasForm from our constants/forms.js file to limit the number of forms being displayed for easier testing
- comments out sentry related client behavior because breaking things in this way made thousands of network requests in seconds and it was impossible to read console messages
- excludes *Form.spec.js so we can have a green build & reintroduce those tests incrementally

### Includes:
Most of this was discussed above -- see files changed for the specifics

### Developer Checklist:
- [X] The code follows the Quality Policy file on Google Drive
- [X] My code has been developer-tested and includes unit tests
- [X] I have considered proper use of exceptions
- [X] I have eliminated IDE warnings
- [X] I have included tasks associated with this pull request in the Sprint Progress Sheet

### Notes:
- Generic forms are downstream from the work all of you are doing so we can get away with keeping it in a separate branch for now until its all ready for dev. If you have concerns about this, let me know!
- A review for this branch would basically be a) verifying tests are complete and pass, b) verifying double field works as expected when changing between routes now, and c) approving of this general approach to handling all these breaking changes.

### CODE REVIEW

**Comment by aneuhold** [comment]
Because this all seems very "work in progress" and it is already merged into a branch that is being worked on, does this need to be pulled into dev? Seems like something that can be worked on in the `GenericForms` branch. It looks like it may make things a bit more confusing for everyone else if this disables a bunch of tests and working functionality at the moment while the rest of the `GenericForms` branch is being worked on.

**Comment by aneuhold** [comment]
Also, feel free to implement as you please. It seems like something we can discuss in reviews when the final product is put together.

**Comment by Tengelma** [comment]
> Because this all seems very "work in progress" and it is already merged into a branch that is being worked on, does this need to be pulled into dev? Seems like something that can be worked on in the `GenericForms` branch. It looks like it may make things a bit more confusing for everyone else if this disables a bunch of tests and working functionality at the moment.

@aneuhold GenericForms is just a copy of Dev atm. The PR is already set up to merge into Generic forms (check out the destination branch). I made this a PR, in spite of that, to get it reviewed and complete the US

**Review by aneuhold — APPROVED** [review]
@Tengelma Ah! Okay didn't notice this was merging into that branch. Definitely approved then.

**Review by vperuzzi — APPROVED** [review]
Tests pass. Double Field bug is resolved and works between create and edit routes as expected. Great work. Approving. ✔️

**Pull request merged**
