### PR TITLE
HM219Sentry

### PR DESCRIPTION
**Pull request by aschnapp**
## Overview
Add sentry to vue and flask

## Includes:
added sentry sdk and main files of python and vue.

## Developer Checklist:
- [x] The code follows the Quality Policy file on Google Drive
- [] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings

## Notes:
division by zero is a test error
Screen Shot 2021-02-05 at 2 27 50 PM
Screen Shot 2021-02-05 at 2 29 30 PM

## Refs:
- [US 216](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-219)

### CODE REVIEW

**Comment by aneuhold** [comment]
How do we access this and where are the screenshots coming from?

**Comment by aschnapp** [comment]
@aneuhold I'll send the info in slack once I get steven's approval. It's sentry's website.

**Comment by aneuhold** [comment]
@aschnapp okay. It wasn't immediately obvious that this was using Steven's account. It would probably be fine to not have everyone get access if that is the only way to view it. There was just no mention of how it was done in the PR.

Is there no way for other people to view it without using Steven's account?

**Comment by aschnapp** [comment]
@aneuhold no, the free tier only supports one user.
I posted the credentials already.

**Comment by aneuhold** [comment]
@aschnapp okay. It looks like right now there are 3 projects in the account. Please see below:

image

The `thm-frontend` and backend ones have errors and look like they make sense. What is the `flask` one hooked up to?

**Comment by aschnapp** [comment]
@aneuhold the backend is the original backend that's currently deployed. Flask is this repo

**Review by aneuhold — APPROVED** [review]
Okay just configured the names to have a `thm-spa` prefix.

**Review by Tengelma — APPROVED** [review]
Looks good to me -- I think the new names are a lot clearer.

**Pull request merged**
