### PR TITLE
U339 Reject Same-Name Models

### PR DESCRIPTION
**Pull request by Tengelma**
### Overview
This implements a 'name in use' validation check for names in the model list & in the create dialog. The check in the model list was a bit quirky and I had to create my own error component instead of leaning on md-field's to avoid issues with the error being hidden by other components (yes, I did tinker with z-values and a number of other solutions before deciding to go this route). This meant making each item in the list a double item so that it could have subtext.

### Includes:
Check files changed.

### Developer Checklist:
- [X] The code follows the Quality Policy file on Google Drive
- [X] My code has been developer-tested and includes unit tests
- [X] I have considered proper use of exceptions
- [X] I have eliminated IDE warnings

### Notes:
- Might be worth introducing some other validation checks (no special characters, no empty field, etc...) but could let Steven do this to get him familiar

### CODE REVIEW

**Review by vperuzzi — APPROVED** [review]

**Review by aneuhold — CHANGES_REQUESTED** [review]
Everything seems to work well but the model name seems to no longer be centered:

image

**Review by aneuhold — CHANGES_REQUESTED** [review]
It looks like it is aligned with the buttons now, but it isn't centered in the list item:

image

**Comment by Tengelma** [comment]
> It looks like it is aligned with the buttons now, but it isn't centered in the list item:
> 
> image

This is intentional. There is a placeholder span beneath it so that it doesn't reformat when the error message pops up. The list item contains space for both.

**Comment by aneuhold** [comment]
@Tengelma could the placeholder span be set to `display:none;` when there isn't an error?

**Comment by aneuhold** [comment]
Its just that it is something that people see first when they open the website up, and having something off-center like that gives it a bad look right off the bat.

**Comment by aneuhold** [comment]
@Tengelma maybe we could have something like this that comes up when the name is already in use? This would allow it to stay centered:

image

Code on this page: https://vuematerial.io/components/input/

**Review by aneuhold — APPROVED** [review]
Alright

**Comment by Tengelma** [comment]
> Alright

Btw, the reason I wasn't seeing what you were pointing out was my monitor. It looks flat white on one monitor and then a distinguishable white box on the other. Kinda weird :man_shrugging:

**Comment by aneuhold** [comment]
@Tengelma oh okay. That makes sense then why it would look fine if it had another box around it.

**Pull request merged**
