### PR TITLE
Us 15 Error Reporting

### PR DESCRIPTION
**Pull request by dblevin1**
### Overview
This User Story implements a custom dialog box to report model errors to the user, it also adds a more in depth Sentry logging abilities.
The original idea was to add a model to the models dialog and check if it has errors. This PR informs the user about the model error on the edit screen and doesn't save the model till the incorrect parameter is fixed.
image
image

Fixes issues:
[111](https://github.com/halomod/TheHaloMod-SPA/issues/111)
[118](https://github.com/halomod/TheHaloMod-SPA/issues/118)
[115](https://github.com/halomod/TheHaloMod-SPA/issues/115)

### Includes:
- client/src/components/Alert.vue
- client/src/components/Graph/index.vue
- client/src/utils/Store.js
- client/src/views/Forms.vue
- server/halomod_app/__init__.py
- server/halomod_app/endpoint_model.py
- server/requirements.txt

### Developer Checklist:
- [x] The code follows the Quality Policy file on Google Drive
- [x] My code has been developer-tested and includes unit tests
- [x] I have considered proper use of exceptions
- [x] I have eliminated IDE warnings
- [x] I have included tasks associated with this pull request in the Sprint Progress Sheet.

### Refs:
- [Ticket](https://ticketlink.com)

### CODE REVIEW

**Review by aneuhold — CHANGES_REQUESTED** [review]
This looks pretty good! There does seem to be an issue though. When deleting the `max` value from `parameter_properties.js` for `lnk_max` and trying something like `1000` for lnk_max, it seems to crash something in the server after taking a very long time. It does provide a helpful error on the client side though:

Client response:

image

Server output after putting in 1000:

image

Then after changing lnk_max back to 10, it still errors out when trying to create the model (it also says that the original model name is taken now):

image

And here is the output of the server:

image

**Comment by dblevin1** [comment]
image
Also added some string manipulation to inform the user where the warning is from.

**Comment by aneuhold** [comment]
@dblevin1 when it errors, it still seems to have saved the model on the server side or maybe just the client side?: 

image

image

It doesn't allow the model to be saved even after the offending parameter is changed back to a normal value. But then after cancelling the model creation, the model was still there on the client side.

**Review by aneuhold — APPROVED** [review]
Looks like it is working a bit better now.

**Pull request merged**
